# **Introduction to Business Analytics**

        
## Titulo

*Group 17*

*Group members* : Georgia Panagopoulou (), Gonçalo Figueira (s263184), Gyorkem Yozgyur (s263126), Teresa Simão (s263065) </p>

-----------------------------------------

## **1. Data Pre-Processing**

-----------------------------------------

### Table of Contents

* [1.1 Importing the Datasets and Libraries](#1.1)
* [1.2 Preliminary Data Analysis and Arrangements](#1.2)
* [1.3 Exploring Data Distributions](#1.3)
* [1.4 Treating Inconsistencies](#1.4)
* [1.5 Feature Engeneering](#1.5)
* [1.6 Data Visualization](#1.6)
* [1.7 Exporting the Datasets](#1.7)

-----------------------------------------

<a id="1.1"></a>
    
## <font color='#FFFFF'>1.1. Importing the datasets and libraries <font>

This section, as mentioned in the title, is intended for importing the data and necessary libraries.

In [30]:
#General Purpose
import pandas as pd

In [31]:
%load_ext autoreload
%autoreload 2
#from Visualizations import *
#from Functions import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [32]:
EV = pd.read_csv('Data/EVChargingStationUsage.csv') 
display(EV.head())

C:\Users\lenovo\AppData\Local\Temp\ipykernel_21128\365961547.py:1: DtypeWarning: Columns (29,30,32) have mixed types. Specify dtype option on import or set low_memory=False.
  EV = pd.read_csv('Data/EVChargingStationUsage.csv')

,Station Name,MAC Address,Org Name,Start Date,Start Time Zone,End Date,End Time Zone,Transaction Date (Pacific Time),Total Duration (hh:mm:ss),Charging Time (hh:mm:ss),...,Longitude,Currency,Fee,Ended By,Plug In Event Id,Driver Postal Code,User ID,County,System S/N,Model Number
0,PALO ALTO CA / HAMILTON #1,000D:6F00:015A:9D76,City of Palo Alto,7/29/2011 20:17,PDT,7/29/2011 23:20,PDT,7/29/2011 23:20,3:03:32,1:54:03,...,-122.160309,USD,0.0,Plug Out at Vehicle,3,95124.0,3284.0,NaN,NaN,NaN
1,PALO ALTO CA / HAMILTON #1,000D:6F00:015A:9D76,City of Palo Alto,7/30/2011 0:00,PDT,7/30/2011 0:02,PDT,7/30/2011 0:02,0:02:06,0:01:54,...,-122.160309,USD,0.0,Customer,4,94301.0,4169.0,NaN,NaN,NaN
2,PALO ALTO CA / HAMILTON #1,000D:6F00:015A:9D76,City of Palo Alto,7/30/2011 8:16,PDT,7/30/2011 12:34,PDT,7/30/2011 12:34,4:17:32,4:17:28,...,-122.160309,USD,0.0,Plug Out at Vehicle,5,94301.0,4169.0,NaN,NaN,NaN
3,PALO ALTO CA / HAMILTON #1,000D:6F00:015A:9D76,City of Palo Alto,7/30/2011 14:51,PDT,7/30/2011 16:55,PDT,7/30/2011 16:55,2:03:24,2:02:58,...,-122.160309,USD,0.0,Customer,6,94302.0,2545.0,NaN,NaN,NaN
4,PALO ALTO CA / HAMILTON #1,000D:6F00:015A:9D76,City of Palo Alto,7/30/2011 18:51,PDT,7/30/2011 20:03,PDT,7/30/2011 20:03,1:11:24,0:43:54,...,-122.160309,USD,0.0,Plug Out at Vehicle,7,94043.0,3765.0,NaN,NaN,NaN

<a id="1.2"></a>
    
## <font color='#FFFFF'>1.2. Preliminary Data Analysis and Arrangements<font>

In this part, we extracted some initial information regarding data types, missing values and memory usage. Also, we conduct basic operations to structure the datasets.

In [33]:
EV.info(memory_usage = 'deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 259415 entries, 0 to 259414
Data columns (total 33 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Station Name                     259415 non-null  object
 1   MAC Address                      259415 non-null  object
 2   Org Name                         259415 non-null  object
 3   Start Date                       259415 non-null  object
 4   Start Time Zone                  259415 non-null  object
 5   End Date                         259415 non-null  object
 6   End Time Zone                    259415 non-null  object
 7   Transaction Date (Pacific Time)  259206 non-null  object
 8   Total Duration (hh:mm:ss)        259415 non-null  object
 9   Charging Time (hh:mm:ss)         259415 non-null  object
 10  Energy (kWh)                     259415 non-null  float64
 11  GHG Savings (kg)                 259415 non-null  float64
 12  Gasoline Savings (gallons)       259415 non-null  float64
 13  Port Type                        259406 non-null  object
 14  Port Number                      259415 non-null  int64
 15  Plug Type                        259415 non-null  object
 16  EVSE ID                          180467 non-null  float64
 17  Address 1                        259415 non-null  object
 18  City                             259415 non-null  object
 19  State/Province                   259415 non-null  object
 20  Postal Code                      259415 non-null  int64
 21  Country                          259415 non-null  object
 22  Latitude                         259415 non-null  float64
 23  Longitude                        259415 non-null  float64
 24  Currency                         257627 non-null  object
 25  Fee                              259415 non-null  float64
 26  Ended By                         259167 non-null  object
 27  Plug In Event Id                 259415 non-null  int64
 28  Driver Postal Code               251013 non-null  float64
 29  User ID                          251738 non-null  object
 30  County                           174750 non-null  object
 31  System S/N                       180467 non-null  float64
 32  Model Number                     180467 non-null  object
dtypes: float64(9), int64(3), object(21)
memory usage: 369.9 MB

In [34]:
# Time-zone distributions, including missing values
print("Start time zones:")
print(EV['Start Time Zone'].value_counts(dropna=False))

print("\nEnd time zones:")
print(EV['End Time Zone'].value_counts(dropna=False))

Start time zones:
Start Time Zone
PDT    166763
PST     92621
UTC        31
Name: count, dtype: int64

End time zones:
End Time Zone
PDT    166791
PST     92623
UTC         1
Name: count, dtype: int64

The Start Time Zone and End Time Zone columns contain different time zones, including PDT, PST and UTC. The data therefore has inconsistent time zone representations both across the two columns and within each column. To ensure consistency and enable accurate comparisons, all timestamps will be converted to a single standard time zone before further analysis.

Converting data types plays a crucial role in optimizing memory efficiency and ensuring compatibility with the chosen machine learning models. By selecting the most appropriate data types, we can reduce memory usage, which is particularly important when dealing with extensive datasets.

Additionally, we make sure that the data types align with the expectations of the machine learning algorithms used, promoting a smooth analysis and modeling process. This practice not only improves project performance but also facilitates more effective decision-making based on the results obtained through machine learning.

That said, and based on the cell above we can conclude that all the variables bellow can be assigned different data types:

<u>Start Date</u>: datetime64[ns]

<u>Start Time Zone</u>:

<u>End Date<u>:

In [35]:
EV = EV.astype({
    # Categorical columns
    'Station Name': 'category',
    'Org Name': 'category',
    'Start Time Zone': 'category',
    'End Time Zone': 'category',
    'Port Type': 'category',
    'Plug Type': 'category',
    'City': 'category',
    'State/Province': 'category',
    'Country': 'category',
    'Currency': 'category',
    'Ended By': 'category',
    'County': 'category',
    'Model Number': 'category',

    # Identifiers: keep as strings, not numeric values
    'MAC Address': 'string',
    'Address 1': 'string',
    'Postal Code': 'string',
    'Driver Postal Code': 'string',
    'User ID': 'string',
    'EVSE ID': 'string',
    'System S/N': 'string',
    'Plug In Event Id': 'string',
    'Port Number': 'string',

    # Numeric measurements
    'Energy (kWh)': 'float64',
    'GHG Savings (kg)': 'float64',
    'Gasoline Savings (gallons)': 'float64',
    'Latitude': 'float64',
    'Longitude': 'float64',
    'Fee': 'float64'
})

In [36]:
EV.info(memory_usage = 'deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 259415 entries, 0 to 259414
Data columns (total 33 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Station Name                     259415 non-null  category
 1   MAC Address                      259415 non-null  string
 2   Org Name                         259415 non-null  category
 3   Start Date                       259415 non-null  object
 4   Start Time Zone                  259415 non-null  category
 5   End Date                         259415 non-null  object
 6   End Time Zone                    259415 non-null  category
 7   Transaction Date (Pacific Time)  259206 non-null  object
 8   Total Duration (hh:mm:ss)        259415 non-null  object
 9   Charging Time (hh:mm:ss)         259415 non-null  object
 10  Energy (kWh)                     259415 non-null  float64
 11  GHG Savings (kg)                 259415 non-null  float64
 12  Gasoline Savings (gallons)       259415 non-null  float64
 13  Port Type                        259406 non-null  category
 14  Port Number                      259415 non-null  string
 15  Plug Type                        259415 non-null  category
 16  EVSE ID                          180467 non-null  string
 17  Address 1                        259415 non-null  string
 18  City                             259415 non-null  category
 19  State/Province                   259415 non-null  category
 20  Postal Code                      259415 non-null  string
 21  Country                          259415 non-null  category
 22  Latitude                         259415 non-null  float64
 23  Longitude                        259415 non-null  float64
 24  Currency                         257627 non-null  category
 25  Fee                              259415 non-null  float64
 26  Ended By                         259167 non-null  category
 27  Plug In Event Id                 259415 non-null  string
 28  Driver Postal Code               251013 non-null  string
 29  User ID                          251738 non-null  string
 30  County                           174750 non-null  category
 31  System S/N                       180467 non-null  string
 32  Model Number                     180467 non-null  category
dtypes: category(13), float64(6), object(5), string(9)
memory usage: 245.9 MB

Check for duplicated rows in the dataset. If they exist remove them, otherwise, don't do anything.

In [37]:
EV.duplicated().sum()

np.int64(4)

In [38]:
duplicates = EV[EV.duplicated(keep=False)]

duplicates.sort_values(by='Plug In Event Id')

,Station Name,MAC Address,Org Name,Start Date,Start Time Zone,End Date,End Time Zone,Transaction Date (Pacific Time),Total Duration (hh:mm:ss),Charging Time (hh:mm:ss),...,Longitude,Currency,Fee,Ended By,Plug In Event Id,Driver Postal Code,User ID,County,System S/N,Model Number
108235,PALO ALTO CA / HIGH #2,0024:B100:0002:5959,City of Palo Alto,2/27/2017 11:14,PST,2/27/2017 14:17,PST,2/27/2017 14:17,3:02:42,2:33:45,...,-122.163017,USD,0.00,Plug Out at Vehicle,1488222853,94301.0,738281,Santa Clara County,164041005417.0,CT4020-HD
108236,PALO ALTO CA / HIGH #2,0024:B100:0002:5959,City of Palo Alto,2/27/2017 11:14,PST,2/27/2017 14:17,PST,2/27/2017 14:17,3:02:42,2:33:45,...,-122.163017,USD,0.00,Plug Out at Vehicle,1488222853,94301.0,738281,Santa Clara County,164041005417.0,CT4020-HD
206764,PALO ALTO CA / BRYANT #5,0024:B100:0002:6D51,City of Palo Alto,4/29/2019 8:10,PDT,4/29/2019 9:09,PDT,4/29/2019 9:10,0:59:06,0:57:54,...,-122.162231,USD,1.33,Plug Out at Vehicle,3413,94027.0,4516921.0,Santa Clara County,170741000000.0,CT4020-HD
206765,PALO ALTO CA / BRYANT #5,0024:B100:0002:6D51,City of Palo Alto,4/29/2019 8:10,PDT,4/29/2019 9:09,PDT,4/29/2019 9:10,0:59:06,0:57:54,...,-122.162231,USD,1.33,Plug Out at Vehicle,3413,94027.0,4516921.0,Santa Clara County,170741000000.0,CT4020-HD
32433,PALO ALTO CA / MPL #6,000D6F00015B7509,City of Palo Alto,2/25/2015 15:24,PST,2/25/2015 15:46,PST,2/25/2015 15:46,0:22:23,0:22:10,...,-122.113457,USD,0.00,Plug Out at Vehicle,469,95134.0,318799.0,NaN,<NA>,NaN
32434,PALO ALTO CA / MPL #6,000D6F00015B7509,City of Palo Alto,2/25/2015 15:24,PST,2/25/2015 15:46,PST,2/25/2015 15:46,0:22:23,0:22:10,...,-122.113457,USD,0.00,Plug Out at Vehicle,469,95134.0,318799.0,NaN,<NA>,NaN
109966,PALO ALTO CA / BRYANT #2,000D:6F00:009D:CFC3,City of Palo Alto,3/10/2017 14:07,PST,3/10/2017 15:53,PST,3/10/2017 15:53,1:46:01,1:24:31,...,-122.162140,USD,0.00,Customer,9453,94065.0,548777,Santa Clara County,102310001132.0,CT2100-HD-CCR
109967,PALO ALTO CA / BRYANT #2,000D:6F00:009D:CFC3,City of Palo Alto,3/10/2017 14:07,PST,3/10/2017 15:53,PST,3/10/2017 15:53,1:46:01,1:24:31,...,-122.162140,USD,0.00,Customer,9453,94065.0,548777,Santa Clara County,102310001132.0,CT2100-HD-CCR

In [39]:
duplicates['Plug In Event Id'].value_counts()

Plug In Event Id
469           2
1488222853    2
9453          2
3413          2
Name: count, dtype: Int64

In [40]:
EV = EV.drop_duplicates().copy()

Missing Values

In [41]:
missing_values = pd.DataFrame({
    'Missing Values': EV.isna().sum(),
    'Percentage Missing (%)': (EV.isna().sum() / len(EV) * 100).round(2)
})

missing_values = missing_values[missing_values['Missing Values'] > 0]

missing_values = missing_values.sort_values(
    by='Percentage Missing (%)',
    ascending=False
)

missing_values

                                 Missing Values  Percentage Missing (%)
County                                    84664                   32.64
EVSE ID                                   78947                   30.43
System S/N                                78947                   30.43
Model Number                              78947                   30.43
Driver Postal Code                         8402                    3.24
User ID                                    7677                    2.96
Currency                                   1788                    0.69
Ended By                                    248                    0.10
Transaction Date (Pacific Time)             209                    0.08
Port Type                                     9                    0.00

<a id="1.4"></a>
    
## <font color='#FFFFF'>1.4. Inconsistencies <font>

Check if there are timezones with end date starting before start date.

Total duration is negative or zero.

Charging time exceeds total duration.

Timestamp-derived duration disagrees substantially with the recorded total duration.

Extremely long occupation times, potentially indicating a vehicle left plugged in after charging.

Negative Values (energy....)


check location